services:
  webauthn:
    image: ghcr.io/openconext/openconext-basecontainers/${WEBAUTHN_PHP_IMAGE:-php72-apache2-node14-composer2:latest}
    volumes:
      - ${WEBAUTHN_CODE_PATH}:/var/www/html
    environment:
      - APP_ENV=dev
